'use client';

import { useState } from 'react';
import { Btn, Field, Modal, useGlobalToast } from '@/components/primitives';
import { C, F } from '@/lib/tokens';

type Template = 'modern' | 'classic' | 'minimal';
type Resume = { name: string; title: string; email: string; phone: string; location: string; link: string; summary: string; skills: string; experience: string; education: string; projects: string; certifications: string };
const blank: Resume = { name: '', title: '', email: '', phone: '', location: '', link: '', summary: '', skills: '', experience: '', education: '', projects: '', certifications: '' };
const designs: { id: Template; label: string; text: string; color: string }[] = [
  { id: 'modern', label: 'Modern', text: 'Bold and contemporary', color: C.saffron },
  { id: 'classic', label: 'Classic', text: 'Traditional and professional', color: C.ink },
  { id: 'minimal', label: 'Minimal', text: 'Clean and spacious', color: C.green },
];
const stepInfo = [['Personal details', 'How should employers contact you?'], ['Professional profile', 'Summarise your strengths and skills.'], ['Background', 'Add your experience and education.'], ['Review & download', 'Check everything before downloading.']];
const lines = (value: string) => value.split('\n').map(x => x.trim()).filter(Boolean);
const skillList = (value: string) => value.split(/,|\n/).map(x => x.trim()).filter(Boolean);
const esc = (value: string) => value.replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[x] || x));

function Preview({ data, design }: { data: Resume; design: Template }) {
  const accent = designs.find(x => x.id === design)?.color || C.saffron;
  const sections = [['Profile', data.summary], ['Experience', data.experience], ['Education', data.education], ['Projects', data.projects], ['Certifications', data.certifications]].filter(x => x[1]);
  const heading = { margin: '0 0 7px', paddingBottom: 5, borderBottom: `1px solid ${accent}55`, color: design === 'classic' ? C.ink : accent, fontSize: 10.5, fontWeight: 800, letterSpacing: '.12em', textTransform: 'uppercase' as const };
  return <div style={{ background: '#fff', minHeight: 650, padding: design === 'minimal' ? 42 : 34, border: `1px solid ${C.line}`, boxShadow: '0 8px 28px rgba(15,14,12,.08)', fontFamily: design === 'classic' ? 'Georgia,serif' : F.ui }}>
    <header style={{ margin: design === 'modern' ? '-34px -34px 26px' : '0 0 25px', padding: design === 'modern' ? '30px 34px' : '0 0 14px', background: design === 'modern' ? accent : '#fff', color: design === 'modern' ? '#fff' : C.ink, borderBottom: design === 'classic' ? `2px solid ${accent}` : undefined }}>
      <div style={{ fontFamily: F.display, fontSize: 28, fontWeight: 700 }}>{data.name || 'Your Name'}</div><div style={{ marginTop: 5, fontSize: 14, fontWeight: 700, color: design === 'modern' ? '#fff' : accent }}>{data.title || 'Professional headline'}</div><div style={{ marginTop: 9, fontSize: 10.5, opacity: .82 }}>{[data.email, data.phone, data.location, data.link].filter(Boolean).join('  •  ') || 'email@example.com  •  +91 00000 00000  •  City'}</div>
    </header>
    {data.skills && <section style={{ marginBottom: 20 }}><h3 style={heading}>Skills</h3><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{skillList(data.skills).map(x => <span key={x} style={{ padding: '4px 8px', borderRadius: 12, background: `${accent}16`, color: accent, fontSize: 10.5, fontWeight: 700 }}>{x}</span>)}</div></section>}
    {sections.map(([title, value]) => <section key={title} style={{ marginBottom: 20 }}><h3 style={heading}>{title}</h3>{lines(value).map((line, i) => <div key={i} style={{ fontSize: 11.5, color: C.ink2, lineHeight: 1.6, marginBottom: 3 }}>{line}</div>)}</section>)}
    {!data.summary && !data.experience && !data.education && <div style={{ padding: '60px 10px', textAlign: 'center', color: C.ink4, fontSize: 12 }}>Your answers will appear here.</div>}
  </div>;
}

export function ResumeBuilderModal({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [design, setDesign] = useState<Template | null>(null); const [step, setStep] = useState(0); const [data, setData] = useState(blank); const toast = useGlobalToast();
  const update = (key: keyof Resume) => (value: string) => setData(old => ({ ...old, [key]: value }));
  const close = () => { onClose(); setTimeout(() => { setDesign(null); setStep(0); setData(blank); }, 200); };
  const documentHtml = () => {
    const color = design === 'classic' ? '#241f1a' : design === 'minimal' ? '#3d7a4f' : '#d97721';
    const section = (title: string, value: string) => value ? `<section><h2>${title}</h2>${lines(value).map(x => `<p>${esc(x)}</p>`).join('')}</section>` : '';
    return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(data.name || 'Resume')}</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#241f1a;line-height:1.45;max-width:760px;margin:auto}header{border-bottom:3px solid ${color};padding-bottom:18px;margin-bottom:22px}h1{font-size:30px;margin:0}header h3{color:${color};margin:5px 0 8px}small{color:#6d665f}h2{font-size:13px;text-transform:uppercase;letter-spacing:1.5px;color:${color};border-bottom:1px solid #ddd;padding-bottom:5px;margin:22px 0 8px}p{font-size:12px;margin:4px 0}.skill{display:inline-block;background:#f5efe8;padding:4px 8px;margin:3px;border-radius:10px;font-size:11px}</style></head><body><header><h1>${esc(data.name)}</h1><h3>${esc(data.title)}</h3><small>${[data.email, data.phone, data.location, data.link].filter(Boolean).map(esc).join(' • ')}</small></header>${data.skills ? `<section><h2>Skills</h2>${skillList(data.skills).map(x => `<span class="skill">${esc(x)}</span>`).join('')}</section>` : ''}${section('Profile', data.summary)}${section('Experience', data.experience)}${section('Education', data.education)}${section('Projects', data.projects)}${section('Certifications', data.certifications)}</body></html>`;
  };
  const download = () => { const url = URL.createObjectURL(new Blob(['\ufeff', documentHtml()], { type: 'application/msword' })); const a = document.createElement('a'); a.href = url; a.download = `${(data.name || 'my-resume').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-resume.doc`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); toast.add('Resume downloaded successfully', 'success'); };
  const printPdf = () => { const popup = window.open('', '_blank'); if (!popup) return toast.add('Please allow pop-ups to save as PDF', 'error'); popup.document.write(documentHtml()); popup.document.close(); popup.focus(); setTimeout(() => popup.print(), 250); };
  return <Modal isOpen={isOpen} onClose={close} title="Resume builder" marathi="रेझ्युमे तयार करा" width={1080}>{!design ? <div><div style={{ textAlign: 'center', marginBottom: 24 }}><h2 style={{ margin: 0, fontFamily: F.display, fontSize: 25 }}>Choose your resume template</h2><p style={{ color: C.ink3, fontSize: 13.5 }}>Pick a design first. You can change it before downloading.</p></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))', gap: 16 }}>{designs.map(item => <button key={item.id} onClick={() => setDesign(item.id)} style={{ border: `1px solid ${C.lineMid}`, borderRadius: 16, background: '#fff', padding: 12, textAlign: 'left', cursor: 'pointer', fontFamily: F.ui }}><div style={{ height: 235, background: '#f8f6f2', borderRadius: 10, padding: 18, borderTop: `14px solid ${item.color}` }}><div style={{ width: '58%', height: 12, background: item.color, marginBottom: 8 }}/><div style={{ width: '42%', height: 6, background: '#bbb', marginBottom: 24 }}/>{[70,95,88,64,92,75].map((w,i) => <div key={i} style={{ width: `${w}%`, height: i === 0 || i === 4 ? 7 : 4, background: i === 0 || i === 4 ? item.color : '#d7d2cc', marginBottom: 8 }}/>)}</div><div style={{ padding: '13px 4px 4px' }}><strong>{item.label}</strong><div style={{ color: C.ink3, fontSize: 12, marginTop: 4 }}>{item.text}</div></div></button>)}</div></div> : <div><div style={{ height: 5, borderRadius: 9, background: C.bgDeep, overflow: 'hidden', marginBottom: 20 }}><div style={{ width: `${((step + 1) / 4) * 100}%`, height: '100%', background: C.saffron }}/></div><div className="mob-stack" style={{ display: 'grid', gridTemplateColumns: 'minmax(280px,.85fr) minmax(360px,1.15fr)', gap: 26, alignItems: 'start' }}><div><div style={{ color: C.saffronDk, fontSize: 11, fontWeight: 800, letterSpacing: '.1em', textTransform: 'uppercase' }}>Step {step + 1} of 4</div><h2 style={{ margin: '5px 0 2px', fontFamily: F.display, fontSize: 23 }}>{stepInfo[step][0]}</h2><p style={{ margin: '0 0 20px', color: C.ink3, fontSize: 13 }}>{stepInfo[step][1]}</p>
    {step === 0 && <><Field label="Full name *" value={data.name} onChange={update('name')} placeholder="e.g. Anuja Karandikar"/><Field label="Professional headline" value={data.title} onChange={update('title')} placeholder="e.g. Product Designer"/><Field label="Email *" type="email" value={data.email} onChange={update('email')} placeholder="you@example.com"/><Field label="Phone" value={data.phone} onChange={update('phone')}/><Field label="Location" value={data.location} onChange={update('location')}/><Field label="LinkedIn or portfolio" value={data.link} onChange={update('link')}/></>}
    {step === 1 && <><Field label="Professional summary" multiline value={data.summary} onChange={update('summary')} placeholder="Write 2–3 sentences about your strengths and goals."/><Field label="Skills" multiline value={data.skills} onChange={update('skills')} placeholder="Product strategy, Figma, Research, Leadership"/></>}
    {step === 2 && <><Field label="Work experience" multiline value={data.experience} onChange={update('experience')} placeholder={'Senior Designer — Company (2022–Present)\nLed a team and improved conversion by 24%.'}/><Field label="Education" multiline value={data.education} onChange={update('education')} placeholder="Degree — University, Year"/><Field label="Projects (optional)" multiline value={data.projects} onChange={update('projects')}/><Field label="Certifications (optional)" multiline value={data.certifications} onChange={update('certifications')}/></>}
    {step === 3 && <div style={{ background: C.greenLt, borderRadius: 12, padding: 16, fontSize: 13, lineHeight: 1.55 }}>Your resume is ready. Download an editable Word file, or choose <strong>Save as PDF</strong> in the print dialog.</div>}
    <div style={{ display: 'flex', gap: 8, marginTop: 22, flexWrap: 'wrap' }}><Btn kind="ghost" onClick={() => step ? setStep(step - 1) : setDesign(null)}>Back</Btn>{step < 3 ? <Btn disabled={step === 0 && (!data.name.trim() || !data.email.trim())} onClick={() => setStep(step + 1)}>Continue</Btn> : <><Btn onClick={download}>Download Word</Btn><Btn kind="outline" onClick={printPdf}>Print / Save PDF</Btn></>}</div></div><div style={{ position: 'sticky', top: 0 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}><span style={{ color: C.ink3, fontSize: 11, fontWeight: 800, textTransform: 'uppercase' }}>Live preview</span><button onClick={() => setDesign(null)} style={{ border: 0, background: 'transparent', color: C.saffronDk, cursor: 'pointer', fontWeight: 700 }}>Change template</button></div><Preview data={data} design={design}/></div></div></div>}</Modal>;
}
